### PR TITLE
Add micropython-micro-gui

### PR DESCRIPTION
**Pull request by tomsci**
From https://github.com/peterhinch/micropython-micro-gui

and integrate with our App model.

### CODE REVIEW

**Comment by tomsci** [comment]
OK I think this is about ready now. Things that work:
* The GUI widgets themselves, proportional fonts, etc
* Integration with our `App` based model, via the new `App` subclass `UguiApp`, including our power saving tricks
* Joystick control to move focus and select widgets (up/down/left/right/select is all ugui supports)
* BUTTON_FRONT to pop the current Screen, or return to the boot menu when no more Screens
* Calling `app.keyboard_prompt()` to get input from the user

Things that don't work:
* Landscape mode or rotation. For now all ugui apps are stuck in portrait mode. ugui doesn't lend itself to the screen size changing dynamically, at any level of the API, and that includes (for now) even defining what mode the app should start in.
* Image rendering. ugui doesn't appear to have any real image support, looks like we'll have to integrate micropython-png as well, or fancy up the st7789 JPG support.

@MatthewWilkes what do you think?

**Comment by MatthewWilkes** [comment]
@tomsci Apologies, thought I'd already commented on this. I'm getting intermittent resets, but I think this might be a RAM issue. The code LGTM, so long as you're not getting resets on your more productioney board.

**Review by MatthewWilkes — APPROVED** [review]

**Comment by tomsci** [comment]
I haven't seen any reset issues myself. I've yet to write anything significant in ugui (I've been C&Ping the examples mostly, for testing) so I'm not sure I have a good feel for what it's actually like to use. But it seems to mostly work and we don't have time to do anything else, so...

**Comment by MatthewWilkes** [comment]
Agreed. I'm _relatively_ confident the resets are a red herring. I say go for it.

**Pull request merged**
